class UserNotFoundError(Exception):
    pass


class UserAlreadyExistError(Exception):
    pass
